<?
$PERM["mission.php"]["2"]="D";
$PERM["mission.php"]["3"]="D";
$PERM["mission.php"]["4"]="D";
$PERM["mission.php"]["5"]="D";
$PERM["mission.php"]["*"]="D";
$PERM["index.php"]["2"]="D";
$PERM["index.php"]["3"]="D";
$PERM["index.php"]["4"]="D";
$PERM["index.php"]["5"]="D";
$PERM["index.php"]["*"]="D";
?>